spring:
  application:
    name: fullstack-car-house
  datasource:
    url: jdbc:h2:mem:fullstackcardb
    username: SA
    password: password
    driver-class-name: org.h2.Driver
  data:
    rest:
      base-path: /api/v1
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect